### PR TITLE
Enable user to filter comments by awul_level 

### PR DESCRIPTION
**Pull request by hasalfernando**
# Description
Fix to Issue #33
1. Allow users to filter the comment "awul_level" as they wish or give them the option to get comments from any "awul_level" (original logic).
2. Stopped generating the same comment on two continuous occasions.

# Motivation and Context
There are times users would need to generate comments from specific categories for specific people.

# Screenshots 
## Web View 1 - Before clicking select
comment-generator
This new select option is added to the UI for the user to select the category.

## Web View 2 - After clicking select
comment-generator-2

## Mobile View 1 - Before clicking select
WhatsApp Image 2020-03-24 at 19 31 23

## Mobile View 2 - After clicking select
WhatsApp Image 2020-03-24 at 19 31 23 (1)

# Main Changes Done
1. Added the filter for the users to filter comments based on categories
2. Stopped a comment from repeating on two continuous occasions

### CODE REVIEW

**Review by janethavi — APPROVED** [review]

**Review by chamathpali — CHANGES_REQUESTED** [review]
Thanks for the PR @hasalfernando ! can you try to make the dropdown consistent among browsers? its different in different browsers, check attached image. I think its better to use the bootstrap custom select? 
image

**Comment by hasalfernando** [comment]
@chamathpali Sure. Will work on that :-)

**Comment by chamathpali** [comment]
@hasalfernando  it doesnt seem to be working. shall we revert it back to the previous commit and let's improve it in the future .

**Comment by hasalfernando** [comment]
@chamathpali sure. I'll revert it.

**Review by chamathpali — APPROVED** [review]

**Comment by chamathpali** [comment]
Thanks 👍

**Pull request merged**
